### ISSUE TITLE
Calling assert.fail instead of fail method

### ISSUE THREAD

**Issue by calbertts** [browserify/commonjs-assert#13]
Hi,

I was wondering if would be more flexible to call the _fail_ method from _assert.fail_ instead of using the internal function directly, in this way would be easier modify the _fail_ default behavior.

Let me know if I'm thinking wrong about this.

Thanks

**Comment by BridgeAR** [comment]
This seems somewhat outdated. We plan to sync this module with the current Node.js master and the internals of assert have changed drastically. Thus, this does not seem to be applicable anymore.
