### ISSUE TITLE
It would be awesome to have closeTo (equals with delta)

### ISSUE THREAD

**Issue by ianomad** [browserify/commonjs-assert#31]

**Comment by calvinmetcalf** [comment]
this is really just a strait up port of the [node assert library](https://nodejs.org/api/assert.html) so if you get them to put it in we'll totally put in in here

**Comment by AJamesPhillips** [comment]
I filed one initial proposal here for the API:  https://github.com/nodejs/node/issues/14686  please weigh in with your opinions of support / suggestions.

**Comment by AJamesPhillips** [comment]
@calvinmetcalf they're against extending the core assert but are all keen for this functionality and for it to extend user land code.  Would you be more open to accepting this in commonjs-assert?

**Comment by AJamesPhillips** [comment]
@calvinmetcalf they're against extending the core assert but are all keen for this functionality and for it to extend user land code. Would you be more open to accepting this in commonjs-assert?

**Comment by lukechilds** [comment]
@AJamesPhillips this module is a direct clone of Node.js assert to work in the browser. We won't support any features that aren't supported in Node.js assert.

If you want this feature it should be added to a different userland package.
