### ISSUE TITLE
Unexpected result from assert.fail

### ISSUE THREAD

**Issue by don01001000** [browserify/commonjs-assert#34]
It seems to me based on the [documentation](https://nodejs.org/api/assert.html#assert_assert_fail_message) that `assert.fail(message)` should throw an exception for which the message property is just the message passed in. However, it's being set to whatever messaged is wrapped in single quotes and followed by ` undefined undefined`.

The output of the above program is as follows:
```
{ [AssertionError: 'boom' undefined undefined]
  name: 'AssertionError',
  actual: 'boom',
  expected: undefined,
  operator: undefined,
  message: '\'boom\' undefined undefined',
  generatedMessage: true }
```

According to the documentation:

> If message is provided only it will be used as the error message, the other arguments will be stored as properties on the thrown object.

**Comment by BridgeAR** [comment]
This is resolved by #44. Please update to v2.0.0.
