### ISSUE TITLE
Strict mode?

### ISSUE THREAD

**Issue by jprichardson** [browserify/commonjs-assert#37]
Node v9.9.0 introduced some changes into the `assert` package. Most notably the introduction of [`strict` mode](https://nodejs.org/api/assert.html#assert_strict_mode).

Would you accept a PR introducing this new functionality and bringing this module up to date?

**Comment by jprichardson** [comment]
If it simplifies the maintenance burden on your end @defunctzombie  - how would you feel about moving this repo to the [`browserify`](https://github.com/browserify) org?

**Comment by defunctzombie** [comment]
@jprichardson I'd be open to that (clearly I have let this module go by the wayside) - what would that require logistically?

**Comment by calvinmetcalf** [comment]
I think you'd have to grant ownership of the project to somebody who is an admin in the browserify org, which would include both me and @jprichardson

**Comment by defunctzombie** [comment]
@calvinmetcalf you are already listed as a collaborator on the repo - is there some other action that "grants ownership" ?

**Comment by calvinmetcalf** [comment]
i just invited you into the browserify org

**Comment by defunctzombie** [comment]
@calvinmetcalf Should I see a notification somewhere for that? I received no email about it.

**Comment by jprichardson** [comment]
I tried to invite you again @defunctzombie. Looks like you were invited by Substack awhile ago. See if you can visit this link: https://github.com/organizations/browserify/settings/profile and if there is something about accepting the invite.

**Comment by defunctzombie** [comment]
@jprichardson I get a 404 when I visit that link.

**Comment by jprichardson** [comment]
@defunctzombie I canceled the invite, and then invited you again. Any email now...?

**Comment by defunctzombie** [comment]
@jprichardson @calvinmetcalf repository transferred. Feel free to remove me from the browserify organization.

**Comment by fabiosantoscode** [comment]
Any updates on this issue?
