### ISSUE TITLE
Can't find variable: process

### ISSUE THREAD

**Issue by rubber-duck-software** [browserify/commonjs-assert#56]
process is generally not defined in the browser environment. Before accessing properties on the process, we should verify process is defined

**Comment by ljharb** [comment]
This is a node module. `process` always exists.

However, if it's not, your bundler might be broken.

**Comment by DetachHead** [comment]
isn't this package supposed to support browsers?
![image](https://user-images.githubusercontent.com/57028336/197102869-decb91f9-e47d-4442-a046-d2355a1c8f76.png)

**Comment by ljharb** [comment]
@DetachHead yes, it does - the way all node modules properly support browsers is by working with the original node module bundler, browserify, and any other non-broken node module bundler.

Broken node module bundlers aren't the concern of package authors.

**Comment by DetachHead** [comment]
i'm using vite, which doen't add `process` by default and i think many other build tools behave the same. imo if a package is targeting browsers it shouldn't assume the bundler will always take care of missing node globals

**Comment by ljharb** [comment]
That means vite is broken. Node packages that target browsers have always assumed that, and as such, that assumption is correct.
